name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Definir nome da imagem
        run: echo "IMAGE_NAME=ghcr.io/alessandra-moreno/todo-api-github-actions:latest" >> $GITHUB_ENV
      - name: Build da imagem
        run: docker build -t $IMAGE_NAME .
      - name: Publicar imagem
        run: docker push $IMAGE_NAME